version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: job-postgres
    restart: always
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - job_pg_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:2.1
    container_name: localstack
    ports:
      - "4566:4566"      # endpoint principal de todos os serviços AWS
      - "4571:4571"      # opcional, alguns SDKs usam portas antigas
    environment:
      - SERVICES=sqs   # só subimos o SQS por enquanto
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  job_pg_data:
  localstack_data: